using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace PainelMesasLivres.Estrutura
{
    public class GeradorNome
    {
        public List<String> GeradorNomes(int Qtde) 
        { 
            List<String> list = new List<String>();

            string[] sexo = { "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F" };

            Random rnd = new Random();

            Random qrnd = new Random();

            for (int i = 0; i < Qtde; i++)
            {
                string FullName = string.Empty;

                if (sexo[rnd.Next(0, sexo.Length - 1)].ToString() == "F")
                {
                    FullName = generete_name_woman();
                }
                else
                {
                    FullName = generete_name_man();
                }
                FullName = FullName +" "+ generete_lastname(qrnd.Next(0, 4)); 
                list.Add(FullName);
            }
            return list;
        }


        protected string generete_name_man()
        {
            Random rnd = new Random();
            string[] name = { "Miguel", "Arthur", "Gael", "Théo", "Heitor", "Ravi", "Davi", "Bernardo", "Noah", "Gabriel" };
            return name[rnd.Next(0, name.Length - 1)].ToString(); ; 
        }
        protected string generete_name_woman()
        {
            Random rnd = new Random();
            string[] name = { "Helena", "Alice", "Laura", "Maria Alice", "Sophia", "Manuela", "Maitê", "Liz", "Cecília", "Isabella" };
            return name[rnd.Next(0, name.Length - 1)].ToString(); ;
        }

        protected string generete_lastname(int Total_LastName)
        {

            string[] lastname = {
                        "Agrisi ",          "Butler ",                   "Hayes ",
                        "Akechi ",          "Caldeira ",                 "Heckert ",
                        "Alencar ",         "Callegari ",                "Henrichsdatter ",
                        "Almeida ",         "Camilete ",                 "Henrichsdt  ",
                        "Altoé ",           "Campos ",                   "Hypólito ",
                        "Alvernaz ",        "Canceglieri ",              "Idalino ",
                        "Alves ",           "Caputo ",                   "Iglesias Machado ",
                        "Amaral ",          "Carminate ",                "Ignácio ",
                        "Ambrozina ",       "Carvalhido ",               "Iki ",
                        "Amélia ",          "Carvalho ",                 "Intringer ",
                        "Amorim ",          "Casaro ",                   "Isgária ",
                        "Andrião ",         "Catabriga ",                "Ivie ",
                        "Apple ",           "Caversani ",                "Ivonete ",
                        "Araújo ",          "Chausse ",                  "Jacoboski ",
                        "Arrivabene ",      "Constâncio ",               "Jacobsen ",
                        "Arseni ",          "Corrêa ",                   "Jacome ",
                        "Baceti ",          "Correia ",                  "Jacomelle ",
                        "Bandeira ",        "da Rocha ",                 "Jacomelli ",
                        "Barcelos ",        "da Silva ",                 "Jambo ",
                        "Basei ",           "Dalcin ",                   "Jensdatter ",
                        "Bastos ",          "D'Altoè ",                  "Jensen ",
                        "Bedore ",          "Dalvin?? ",                 "Jorge ",
                        "Bellè ",           "Dassié ",                   "Kiepper ",
                        "Bellon ",          "de Aguiar ",                "Kilpatrick ",
                        "Bena? ",           "de Albergaria ",            "Kirmse ",
                        "Berger ",          "De Angeli ",                "Kister ",
                        "Bernabé ",         "de Assis ",                 "Klein ",
                        "Bertolosso ",      "de Avila ",                 "Klippel ",
                        "Betini ",          "de Azeredo ",               "Knudsen ",
                        "Brito ",           "de Azevedo Fernandes ",     "Kolberg ",
                        "Mariani ",               "De Biase ",                 "La Point ",
                        "Marinho ",                "Olerdatter ",                             "Lacerda ",
                        "Maroto ",                 "Olimpio ",                            "Lachini ",
                        "Marquioro ",              "Oliveira ",                               "Ladeira ",
                        "Martins de Almeida ",     "Orsato ",                                        "Lage ",
                        "Mascarelo ",              "Pacheca ",                               "Lans ",
                        "Massari ",                "Pacheco ",                             "Laura ",
                        "Mergár ",                 "Pachequa ",                            "Laus ",
                        "Mesquita ",               "Paes ",                              "Leite ",
                        "Nacaratti ",              "Pagani ",                               "Leme ",
                        "Nagem ",                  "Paganini Merisio ",                           "Liberator ",
                        "Nakamurada ",             "Pagiola ",                                "Loredetto ",
                        "Nalli ",                  "Pancot ",                           "Lott ",
                        "Napoleão ",               "Pariz ",                              "Lovatel ",
                        "Nardini ",                "Pastore ",                             "Luis ",
                        "Nascimento ",             "Pedersdatter ",                                "Machado  ",
                        "Nielsdatter ",            "Penido ",                                 "Mafra ",
                        "Nielsen ",                "Perez ",                             "Maifredi ",
                        "Ockerman ",               "Perreyra ",                              "Majeski ",
                        "Ogura ",                  "Peterle ",                           "Manoel ",
                        "Oinhos ",                 "Possebon ",                            "Mantoan ",
                        "Olausdatter ",            "Marchiori ",                  "Olausen ",
                        "Quartezani ",             "Wainer ",
                        "Queiroz ",                "Walker ",
                        "Quinelato ",              "Wallory ",
                        "Quirino ",                "Wandermurem ",
                        "Rabbi ",                  "Warner ",
                        "Rabello ",                "Wash ",
                        "Rabelo ",                 "Watanabe ",
                        "Ragazzi ",                "Weiss ",
                        "Rasmussen ",              "Zacchi ",
                        "Renzo ",                  "Zaganelli ",
                        "Resende ",                "Zaia ",
                        "Rigon ",                  "Zambão ",
                        "Rivero ",                 "Zambon ",
                        "Rodrigues ",              "Zamparoni ",
                        "Romanini ",               "Zampiroli ",
                        "Rosa ",                   "Zanelato ",
                        "Rubens ",                 "Zantonelli ",
                        "Sa ",                     "Zerboni ",
                        "Sacramento ",             "Zucatelli ",
                        "Sampaio ",                "Abaine ",
                        "Santa Ana ",              "Abaurre ",
                        "Santos ",                 "Abbud ",
                        "Sartori ",                "Abecassis ",
                        "Savignon ",               "Aboudib ",
                        "Scarcinelli ",            "Abraão ",
                        "Scoot ",                  "Abreu Lisboa ",
                        "Selvatici ",              "Abreu ",
                        "Serafim ",                "Acátolli ",
                        "Shoel ",                  "Aggrizzi ",
                        "Silotti ",                "Agrisi Merisio ",
                        "Silva ",                  "Agrizi ",
                        "Sodre ",                  "Agrizi, Neto ",
                        "Tagliaferro ",            "Agrizzi Viana Calmon Viana ",
                        "Targa ",                  "Agrizzi ",
                        "Targonato ",              "Aguiar ",
                        "Tassinari ",              "Aiette Malo ",
                        "Taufner ",                "Aiette ",
                        "Tavares ",                "Airoso ",
                        "Teves ",                  "Alázia ",
                        "Thom ",                   "Alba ",
                        "Tomé ",                   "Albani ",
                        "Tosi ",                   "Alberico ",
                        "Trave ",                               "Armellin ",
                        "Turra ",                               "Arpini ",
                        "Ultramar ",                            "Arrivabene ",
                        "Urbino ",                              "Arruda ",
                        "Vaccari ",                             "Assis ",
                        "Vadagnin ",                            "Assú ",
                        "Valani ",                              "Assumpção ",
                        "Valdino ",                             "Assunção ",
                        "Valvassori ",                          "Augusto ",
                        "Vargas ",                              "Augustsdatter ",
                        "Vasconcelos ",                         "Augustsen ",
                        "Ventorim Iglesias ",                   "Avelar ",
                        "Verret ",                              "Aveleda ",
                        "Viana ",                               "Avila ",
                        "Viçosi ",                              "Azevedo ",
                        "Vieira ",                              "Bachetti ",
                        "Villela ",                             "Badaró ",
                        "Amim ",                                "Badr ",
                        "Amorim Coutinho ",                     "Baiense ",
                        "Amorim ",                              "Balança ",
                        "Anchesqui ",                           "Balarini ",
                        "Andersdatter ",                        "Baldo ",
                        "Andersen ",                            "Baldotto ",
                        "Andrade ",                             "Balestre ",
                        "Andreão ",                             "Baliana ",
                        "Andreasdatter ",                       "Ballarini ",
                        "Angelo ",                              "Banhos Pereira ",
                        "Anna ",                                "Baptista ",
                        "Antonia ",                             "Baquete ",
                        "Antoniazzi ",                          "Barazzuol ",
                        "Antônio ",                             "Barbato ",
                        "Antunes Fernandes  ",                  "Barbosa da Silva ",
                        "Antunes ",                             "Barbosa ",
                        "Apolinário ",                          "Barboza ",
                        "Apolonio ",                            "Barcellos ",
                        "Appolinario ",                         "Barnabe ",
                        "Araújo ",                              "Barnett ",
                        "Ardizzon ",                            "Baro ",
                        "Arduíni ",                             "Barone ",
                        "Armani ",                              "Barrazuol ",
                        "Barrazzuol ",                          "Bernardo ",
                        "Barreira ",                            "Brogan ",
                        "Barreto ",                             "Brum ",
                        "Barros ",                              "Brumana ",
                        "Barroso ",                             "Bruneli ",
                        "Basoni ",                              "Brunelli ",
                        "Bassan ",                              "Bruno ",
                        "Bassani ",                             "Bruschi ",
                        "Bassetti ",                            "Brusco ",
                        "Basso ",                               "Brush ",
                        "Bassos ",                              "Brusque ",
                        "Bassul ",                              "Bubach ",
                        "Bastianelli ",                         "Bueno ",
                        "Bastione ",                            "Buffalo ",
                        "Batista ",                             "Buffo ",
                        "Battaglia ",                           "Bullock ",
                        "Battagnoli ",                          "Buoro ",
                        "Battistela ",                          "Buque ",
                        "Battistella ",                         "Burgues ",
                        "Battisti ",                            "Burrows ",
                        "Baucher ",                             "Busato ",
                        "Bazoni ",                              "Busetti ",
                        "Bedard ",                              "Buson ",
                        "Belcavello ",                          "Buzatto ",
                        "Belinato ",                            "Buzon ",
                        "Belli ",                               "Caballero ",
                        "Bellini ",                             "Cabral ",
                        "Bellon ",                              "Caetano ",
                        "Belmock ",                             "Calabrez ",
                        "Beltrame ",                            "Calabreza ",
                        "Beltran ",                             "Calassara ",
                        "Belz ",                                "Calatrone ",
                        "Benedetti ",                           "Calazans ",
                        "Benevenutte ",                         "Caldana ",
                        "Benevides ",                           "Caldo ",
                        "Benica ",                              "Calegari ",
                        "Beninca ",                             "Calegario ",
                        "Beraldo ",                             "Caliari ",
                        "Berard Lepine ",                       "Califfe ",
                        "Berg ",                                "Calil ",
                        "Bergami ",                             "Calimam ",
                        "Bernabé ",                             "Caliman ",
                        "Bernadini ",                           "Calixto ",
                        "Bernadot ",                            "Calliman ",
                        "Bernardes ",                           "Calmon ",
                        "Bernardi ",                            "Calotto ",
                        "Bernardini ",                          "Calvi ",
                        "Casteluber ",                          "Camara ",
                        "Castro ",                              "Camargo ",
                        "Catellan ",                            "Camata ",
                        "Cattai ",                              "Camatta ",
                        "Cattelan ",                            "Cambiage ",
                        "Cavalcanti ",                          "Camiletti ",
                        "Cavaleiro ",                           "Camillete ",
                        "Cavallina ",                           "Campagnaro ",
                        "Cavanelas ",                           "Camporês ",
                        "Cavatti ",                             "Camporez ",
                        "Cavazzan ",                            "Campos ",
                        "Ceccon ",                              "Canal ",
                        "Cecília Lorenzoni ",                   "Canata ",
                        "Cecote ",                              "Canata, Netto ",
                        "Cecotti ",                             "Cancian ",
                        "Cei ",                                 "Candido ",
                        "Celot ",                               "Cansi ",
                        "Cenedesi ",                            "Cansian ",
                        "Ceolin ",                              "Cansio ",
                        "Ceotto ",                              "Canzian ",
                        "Cergueira ",                           "Capelini ",
                        "Cerqueira ",                           "Caprini ",
                        "Cervantes ",                           "Capucho ",
                        "Ceschel ",                             "Carazas ",
                        "Cescon ",                              "Carbonara ",
                        "Cesconeto ",                           "Cardosa ",
                        "Cesconetto ",                          "Cardoso ",
                        "Cevolani ",                            "Cardozo ",
                        "Chagas ",                              "Careta ",
                        "Chapiniti ",                           "Caretta ",
                        "Chaves ",                              "Caridade ",
                        "Cheibub ",                             "Carlesso ",
                        "Chiaradia ",                           "Carminati ",
                        "Chiarellotto ",                        "Carmo ",
                        "Chiecan ",                             "Carneiro ",
                        "Chiecon ",                             "Carniele ",
                        "Chies ",                               "Carnielle ",
                        "Chiesurin ",                           "Carnielli ",
                        "Christ ",                              "Carrasco ",
                        "Christensdatter ",                     "Carrer ",
                        "Christensen ",                         "Carriço ",
                        "Christiandatter ",                     "Carvalho ",
                        "Christiansdatter ",                    "Casado Gama ",
                        "Christiansen ",                        "Casagrande ",
                        "Christophersen ",                      "Casaro ",
                        "Chtistensdatter ",                     "Cassaro ",
                        "Cipriano ",                            "Cassini ",
                        "Ciqueira ",                            "Castelione ",
                        "Cittera ",                              "Dariva ",
                        "Claudino ",                             "Daroz ",
                        "Cobo ",                                 "Darroz ",
                        "Cocco ",                                "Davel ",
                        "Coco ",                                 "David ",
                        "Codesso ",                              "de Abreu ",
                        "Coelho ",                               "De Agnoi ",
                        "Côgo ",                                 "De Agnoi/ De Angeli ",
                        "Cola ",                                 "De Agostini ",
                        "Coladeci ",                             "de Albernas ",
                        "Colato ",                               "de Albernaz ",
                        "Coleti ",                               "de Almada ",
                        "Collaço ",                              "de Almeida ",
                        "Colli ",                                "De Almeyda ",
                        "Colluse ",                              "de Alvarenga ",
                        "Collusse ",                             "de Amigo ",
                        "Colodeta ",                             "de Andrade ",
                        "Colodete ",                             "de Andrades ",
                        "Colodetti ",                            "De Angeli, Neto ",
                        "Colombi ",                              "de Arajuo ",
                        "Comarela ",                             "de Araújo ",
                        "Comerio ",                              "de Assis ",
                        "Conceicao ",                            "de Augustinho ",
                        "Conciani ",                             "de Avila ",
                        "Conde ",                                "de Ayrosa ",
                        "Congo ",                                "de Azebedo ",
                        "Constantini ",                          "de Azedias ",
                        "Constantino ",                          "de Azevedo Fernandes ",
                        "Contarato ",                            "de Azevedo ",
                        "Contarini ",                            "de Barcellos ",
                        "Conte ",                                "de Barros ",
                        "Conterini ",                            "de Bem ",
                        "Conti ",                                "De Biasi ",
                        "Coppo ",                                "de Brito ",
                        "Corcos ",                               "de Camargo ",
                        "Cordeiro ",                             "de Candia ",
                        "Corneti ",                              "de Carvalho ",
                        "Corocher ",                             "de Castro ",
                        "Corradi ",                              "de Chaves ",
                        "Correa e Castro ",                      "De Conto ",
                        "Corrêa ",                               "de Deus ",
                        "Correia ",                              "de Eslo Banhos ",
                        "Correya ",                              "de Faria ",
                        "Corte ",                                "de Farias ",
                        "Cosme ",                                "de Figueiredo ",
                        "Cosseti ",                              "de Freitas ",
                        "Costa Braga ",                          "de Godoy ",
                        "Costa Longa ",                          "de Góes ",
                        "Costa Longo ",                          "de Gois ",
                        "Costa ",                                "de Gouvea ",
                        "Costalonga ",                           "de Jesus ",
                        "Costariol ",                            "De Kardin ",
                        "Cota ",                                 "de Lemos ",
                        "Coutinho ",                             "de Lima ",
                        "Covre ",                                "de Magalhães ",
                        "Cozumeco ",                             "de Maia ",
                        "Cravellar ",                            "de Marchi ",
                        "Cremard ",                              "de Martin ",
                        "Cremasco ",                             "de Martins ",
                        "Cressafe ",                             "de Matos ",
                        "Cricco ",                               "de Mattos ",
                        "Crosali ",                              "de Medeiros ",
                        "Crozatti ",                             "de Mello ",
                        "Cruz ",                                 "de Melo ",
                        "Cuman ",                                "de Mendonça ",
                        "Cunha ",                                "de Miranda ",
                        "Cunshnir ",                             "de Moraes ",
                        "Curbani ",                              "de Morais ",
                        "Curcio ",                               "De Mori ",
                        "Curitiba ",                             "de Moura ",
                        "Custódio ",                             "de Nadai ",
                        "Cypriano ",                             "De Nardi ",
                        "Cyrillo ",                              "de Oliveira Alves ",
                        "da Camara ",                            "de Oliveira Fernandes ",
                        "da Conceicao ",                         "de Oliveira ",
                        "da Costa ",                             "de Olivença ",
                        "da Cunha ",                             "de Oliveria ",
                        "Da Dalt ",                              "de Oliviera ",
                        "da Fraga ",                             "De Osti ",
                        "da Gama ",                              "de Paiva ",
                        "da Gloria ",                            "de Palma ",
                        "Da Pacciani ",                          "De Paoli ",
                        "da Ros ",                               "de Paula ",
                        "da Rosa ",                              "de Pierro ",
                        "da Silva ",                             "De Poli ",
                        "da Silveira ",                          "De Pra ",
                        "Dadalto ",                              "de Queirós ",
                        "D'Agostini ",                           "de Queiroz ",
                        "D'Agostino ",                           "de Sa ",
                        "Dal Bo ",                               "de Santa Rosa ",
                        "Dal Cin ",                              "de São Thomé ",
                        "Dal Fior ",                             "de Siqueira ",
                        "Dal Piaz ",                             "de Sousa Mendonça ",
                        "Dalla Betta Berta ",                    "de Sousa ",
                        "Dalla Marta ",                          "de Souza Correa ",
                        "Dalla ",                                "de Souza ",
                        "Dall'armellina ",                       "De Stefani ",
                        "Dall'ava ",                             "de Vargas ",
                        "Dalsiza ",                              "de Vasconcellos ",
                        "Dalto ",                                "de Vasconcelos ",
                        "Daltro ",                               "De Vecchi ",
                        "Dalvi ",                                "de Zan ",
                        "Dan ",                                  "Debona ",
                        "Dancy ",                                "Del Puppo ",
                        "Dansi ",                                "Delai ",
                        "Dantas ",                               "Delaparte ",
                        "Danzi ",                                "Delarmelina ",
                        "Dardengo ",                             "Delazare ",
                        "Della Coletta ",                        "Delfior ",
                        "Francisca ",                      "Della Libera ",
                        "Francischeto ",                   "Dell'Antonia ",
                        "Francischetto ",                  "Dellaparte ",
                        "Francisco ",                      "Delpupo ",
                        "Francisqueti ",                   "Demartins ",
                        "Francisqueto ",                   "Demoni ",
                        "Franco ",                         "Denadai ",
                        "Frandsen ",                       "Deprá ",
                        "Frattini ",                       "Deschievane ",
                        "Frazão ",                         "Dessaure ",
                        "Fregolent ",                      "Destéfani ",
                        "Freire ",                         "di Balliana ",
                        "Freitas ",                        "di Barrel ",
                        "Freyre ",                         "di Boscarato ",
                        "Friao? ",                         "Di Girolamo ",
                        "Friezell ",                       "Dias ",
                        "Friezelle ",                      "Diirr ",
                        "Friggi ",                         "Dinis ",
                        "Frizi ",                          "do Amparo ",
                        "Frizzera ",                       "do Bem ",
                        "Frizzo ",                         "do Bom Sucesso ",
                        "Frossar ",                        "do Bonfim ",
                        "Fruett ",                         "do Carmo ",
                        "Fulaneti ",                       "do Couto ",
                        "Fumaneri ",                       "do Espi?rito Santo ",
                        "Fumanesi ",                       "do Espirito Santo ",
                        "Fundão ",                         "do Lago ",
                        "Furian ",                         "do Nascimento Machado ",
                        "Furlan ",                         "do Nascimento ",
                        "Furtado ",                        "do Prado ",
                        "Fusinato ",                       "do Rosário ",
                        "Fuzeti ",                         "do Sacramento ",
                        "Fuzetto ",                        "Doimo ",
                        "Galavotti ",                      "Dolfi ",
                        "Galina ",                         "Dolôres ",
                        "Gallina ",                        "Domene ",
                        "Gallo ",                          "Domingues ",
                        "Galvão ",                         "Domo ",
                        "Garcia ",                         "Donadelli ",
                        "Gardiman ",                       "Donadello ",
                        "Gargan ",                         "Donadira ",
                        "Gaspar ",                         "Donald ",
                        "Gasparello ",                     "Donati ",
                        "Gasparini ",                      "Donato ",
                        "Gato ",                           "Dorigo ",
                        "Gaucci ",                         "Dorzenoni ",
                        "Gava ",                           "dos Reis ",
                        "Gavina ",                         "dos Santos ",
                        "Gazola ",                         "Du Pin ",
                        "Gentina ",                        "Duar ",
                        "George ",                         "Duarte ",
                        "Geraldo ",                        "Duque ",
                        "Ghivan ",                         "Durfee ",
                        "Giacomele ",                      "Dutra ",
                        "Giacomeli Rezende ",              "Entringer ",
                        "Giacomelli ",                     "Erbolato ",
                        "Giobini ",                        "Ervati ",
                        "Giovannetti ",                    "Esméria ",
                        "Giro ",                           "Especemile ",
                        "Giuduce ",                        "Espi?rito Santo ",
                        "Giuriato ",                       "Espíndula ",
                        "Giuriatto ",                      "Espineli ",
                        "Givelli ",                        "Espinola ",
                        "Gobbi ",                          "Espinosa ",
                        "Gobbo ",                          "Espirito Santo ",
                        "Gobi ",                           "Esteves ",
                        "Goese ",                          "Evarti ",
                        "Gomes de Azevedo ",               "Fabre ",
                        "Gomes Luis ",                     "Fabro ",
                        "Gomes ",                          "Faccini ",
                        "Gonçalves ",                      "Faccitin ",
                        "Gonçalvez ",                      "Fachini ",
                        "Gonzalves ",                      "Faco ",
                        "Gosepi ",                         "Facundes ",
                        "Gottardo ",                       "Faé ",
                        "Graça ",                          "Fagundes ",
                        "Grando ",                         "Falchetto ",
                        "Grand-Pre ",                      "Falqueto ",
                        "Granzottin ",                     "Falsoni ",
                        "Granzotto ",                      "Farace ",
                        "Grasseto ",                       "Fardim ",
                        "Grassi ",                         "Fardin ",
                        "Greco ",                          "Faria ",
                        "Gregio ",                         "Farias ",
                        "Gregolin ",                       "Faroni ",
                        "Gretti ",                         "Fasoli ",
                        "Griffo ",                         "Fassarella ",
                        "Grillo ",                         "Favatto ",
                        "Grobério ",                       "Favero ",
                        "Grolla ",                         "Favoreto ",
                        "Guarnier ",                       "Fazoli ",
                        "Gueberio ",                       "Fazollo ",
                        "Guedes ",                         "Fazôlo ",
                        "Guerini ",                        "Feitoza ",
                        "Guerino ",                        "Felet ",
                        "Guerra ",                         "Felete ",
                        "Guidini ",                        "Ferdinando ",
                        "Guidolini ",                      "Ferlin ",
                        "Guilherme ",                      "Fernandes ? ",
                        "Guimarães Braga ",                "Fernandes ",
                        "Guisso ",                         "Fernandez ",
                        "Guizzardi ",                      "Ferraco ",
                        "Gularte ",                        "Ferrão ",
                        "Guldbrandsdatter ",               "Ferrarese ",
                        "Habib ",                          "Ferrari ",
                        "Henrichsen ",                     "Ferreira Braga ",
                        "Henrique ",                       "Ferrighetto ",
                        "Henriques ",                      "Ferro ",
                        "Herculano ",                      "Feu ",
                        "Herman ",                         "Fidelis ",
                        "Herzog ",                         "Figueira ",
                        "Hoffman ",                        "Figueredo ",
                        "Hoffmann ",                       "Filete ",
                        "Holliday ",                       "Fileti ",
                        "Horacio ",                        "Fillinger ",
                        "Hostey ",                         "Fim ",
                        "Iglesias Machado ",               "Fioravante ",
                        "Iwand ",                          "Fioresi ",
                        "Jacinto ",                        "Fioreti ",
                        "Jesus ",                          "Fioretti ",
                        "Jeus ",                           "Fiorez ",
                        "Joao ",                           "Fiorido ",
                        "Joaquina ",                       "Fiorim ",
                        "Joensdatter ",                    "Fiorini ",
                        "Johannesdt  ",                    "Fiório ",
                        "Johannesen ",                     "Fiorot ",
                        "Johansdatter ",                   "Fiorotto ",
                        "Johansen ",                       "Firese ",
                        "Jonsson ",                        "Firme ",
                        "Jordão ",                         "Fitipaldi ",
                        "Jorgensen ",                      "Fittipaldi ",
                        "Josefa ",                         "Flora ",
                        "Julio ",                          "Flozillo ",
                        "Justi ",                          "Foffi ",
                        "Justo ",                          "Fonseca ",
                        "Juvanhol ",                       "Fontana ",
                        "Kiefer ",                         "Fontes ",
                        "Kristensen ",                     "Forafo ",
                        "Kristiansen ",                    "Formigoni ",
                        "Kuiger ",                         "Fornazier ",
                        "Küster ",                         "Frachin ",
                        "Lage ",                           "Fraga ",
                        "Lago ",                           "Frais ",
                        "Lagoeiro ",                       "Franceschet ",
                        "Laiberetor ",                     "Franceschetto ",
                        "Lamha ",                          "Franchin ",
                        "McCune ",                          "Landeira ",
                        "Meato ",                           "Lanes ",
                        "Medeiros ",                        "Langrin ",
                        "Meger ",                           "Lapa ",
                        "Meira ",                           "Largura ",
                        "Meirelles ",                       "Larsdatter ",
                        "Melegari ",                        "Larsen ",
                        "Mello Cortezia ",                  "Laurenco ",
                        "Mello ",                           "Laures ",
                        "Melo ",                            "Laus ",
                        "Mendes ",                          "Lay ",
                        "Mendonça ",                        "Lazarin ",
                        "Menegardo ",                       "Leal ",
                        "Meneghin ",                        "Légora  ",
                        "Meneguete ",                       "Leitão ",
                        "Meneses ",                         "Leite ",
                        "Menezes ",                         "Lemos ",
                        "Mengale ",                         "Lems ",
                        "Mereciano ",                       "Leonardes ",
                        "Merenciano ",                      "Leonel ",
                        "Mergár ",                          "Leopoldo ",
                        "Merigue ",                         "Lepine ",
                        "Merotto ",                         "Lerner ",
                        "Mesquita ",                        "Lessa ",
                        "Michelsen or Mikkelsen ",          "Libardi ",
                        "Milanez ",                         "Liberatori ",
                        "Milaneze ",                        "Liduino ",
                        "Milanezi ",                        "Lima ",
                        "Milena ",                          "Lingiardi ",
                        "Miller ",                          "Lino ",
                        "Minatel ",                         "Lisboa ",
                        "Minet ",                           "Lizabo ",
                        "Minete ",                          "Longo ",
                        "Minette ",                         "Lopes ",
                        "Minetti ",                         "Lorenção ",
                        "Miniguite ",                       "Lorencini ",
                        "Miniguiti ",                       "Lorençon ",
                        "Miolla ",                          "Lorenzini ",
                        "Miquelin ",                        "Lorenzon ",
                        "Miranda ",                         "Lorenzoni ",
                        "Mistura ",                         "Loreto ",
                        "Mizzoni ",                         "Lorezon ",
                        "Modesto ",                         "Loss ",
                        "Modolo ",                          "Lougun ",
                        "Moitinho ",                        "Loura ",
                        "Mol ",                             "Loureiro ",
                        "Molinaroli ",                      "Lourença ",
                        "Monente ",                         "Lourenção ",
                        "Monfardini ",                      "Lourenço ",
                        "Moniz ",                           "Lourneco ",
                        "Monstans ",                        "Louzada ",
                        "Montanaro ",                       "Lovat ",
                        "Monteiro ",                        "Lovatti ",
                        "Montemor ",                        "Lozano ",
                        "Montezano ",                       "Lubiana ",
                        "Montoan ",                         "Luca ",
                        "Moraes ",                          "Lucas ",
                        "Morais ",                          "Lucca ",
                        "Moreira ",                         "Lucchetta ",
                        "Morelo ",                          "Luchi ",
                        "Moresco ",                         "Luciano ",
                        "Morgan ",                          "Luiz ",
                        "Mork ",                            "Lunz ",
                        "Mørk ",                            "Lupino ",
                        "Moro ",                            "Luzorio ",
                        "Morosini ",                        "Lyrio ",
                        "Mortensdatter ",                   "M ",
                        "Mortensen ",                       "Macatrozzi ",
                        "Moschon ",                         "Mace ",
                        "Moscon ",                          "Macedo ",
                        "Moser ",                           "Machado ",
                        "Mosquini ",                        "Maciel ",
                        "Mosso ",                           "Madsdatter ",
                        "Moulin ",                          "Madsen ",
                        "Moura ",                           "Madureira ",
                        "Moura, Filho ",                    "Magaldi ",
                        "Moyses ",                          "Magalhães ",
                        "Mozer ",                           "Magnago ",
                        "Muniz de Resende ",                "Magri ",
                        "Muniz ",                           "Magrini ",
                        "Muraro ",                          "Magro ",
                        "Muscareli ",                       "Mahtielo ",
                        "Mutk ",                            "Maia ",
                        "Nassar ",                          "Maida ",
                        "Nelson ",                          "Majeveski ",
                        "Nerg ",                            "Malini ",
                        "Néspoli ",                         "Malta ",
                        "Neto ",                            "Malvezzi ",
                        "Netto ",                           "Mamoni ",
                        "Neves ",                           "Maneback ",
                        "Nicole ",                          "Manfredo ",
                        "Nicoli ",                          "Manhães ",
                        "Nicolini ",                        "Manoel ",
                        "Nielsdatter ",                     "Mantovali ",
                        "Nielson ",                         "Marabote ",
                        "Nogueira ",                        "Maragon ",
                        "Noronha ",                         "Marangon ",
                        "Nosè ",                            "Maranguanhe ",
                        "Novaes ",                          "Marcantonio ",
                        "Novais ",                          "Marcarini ",
                        "Novo ",                            "Marchese ",
                        "Nucci ",                           "Marchetti ",
                        "Nunes ",                           "Marchioro ",
                        "Oliveira Braga ",                  "Marchiotto ",
                        "Oliveira Costa ",                  "Marcon ",
                        "Oliveira ",                        "Maremiori ",
                        "Oliveria ",                        "Marett ",
                        "Olsdatter ",                       "Maretto ",
                        "Olsen ",                           "Maria ",
                        "Ongaro ",                          "Mariane ",
                        "Onhas ",                           "Marianelli ",
                        "Orechio ",                         "Marim ",
                        "Orelio ",                          "Marin ",
                        "Orletti ",                         "Marinato ",
                        "Ormo ",                            "Marinho ",
                        "Osthed ",                          "Marini ",
                        "Ostigui Domingue ",                "Mariotto ",
                        "Ostiguy Domingue ",                "Mark ",
                        "Ostitty ",                         "Marochio ",
                        "Ostity Domingue ",                 "Maróquio ",
                        "Pagot ",                           "Marotto ",
                        "Pagoto ",                          "Marques ",
                        "Pagotte ",                         "Marquette ",
                        "Pagotto ",                         "Marsal ",
                        "Paiva ",                           "Martas ",
                        "Paixão ",                          "Martha ",
                        "Pajot ",                           "Martin ",
                        "Palermo ",                         "Martinatti ",
                        "Palù ",                            "Martins ",
                        "Panciere ",                        "Martinsdatter ",
                        "Pancini ",                         "Martinsen ",
                        "Pandini ",                         "Martinussu ",
                        "Panetto ",                         "Mascarello ",
                        "Panhoca ",                         "Mascarelo ",
                        "Pantaroto ",                       "Mascarenhas ",
                        "Paoliello ",                       "Maset ",
                        "Parent ",                          "Masioli ",
                        "Parente ",                         "Massardi ",
                        "Paresque ",                        "Mastela ",
                        "Paresqui ",                        "Mastella ",
                        "Partele ",                         "Mastrantoni ",
                        "Partelli Codesso ",                "Masut ",
                        "Partelli Lima ",                   "Mateus ",
                        "Partelli ",                        "Mathias ",
                        "Pasca ",                           "Mathiasso ",
                        "Pase ",                            "Mathiello ",
                        "Pasocco ",                         "Mathiélo ",
                        "Passamani ",                       "Mathisen ",
                        "Passos ",                          "Matiello ",
                        "Patricio ",                        "Matielo ",
                        "Paulina ",                         "Matioz ",
                        "Paulo ",                           "Matos ",
                        "Pauluccio ",                       "Matsuschita ",
                        "Pavan ",                           "Mattar ",
                        "Pazeto ",                          "Mauro ",
                        "Pazetto ",                         "Mazzoco ",
                        "Pazini ",                          "Mazzon ",
                        "Vekar ",                             "Speranza ",
                        "Veloso ",                            "Sperato ",
                        "Vendermiatti ",                      "Sperotto ",
                        "Ventorim Iglesias ",                 "Spigolon ",
                        "Ventorim ",                          "Stebenne ",
                        "Ventura ",                           "Steele ",
                        "Venturim Iglesias Cortezia ",        "Stefani ",
                        "Venturim Iglesias ",                 "Stein ",
                        "Venturim ",                          "Stelzer ",
                        "Venturin ",                          "Strabelli ",
                        "Venturini ",                         "Stradiotto ",
                        "Vereza ",                            "Stringuine ",
                        "Veronese Rezende ",                  "Strozzi ",
                        "Verotti ",                           "Suave ",
                        "Vertuane ",                          "Surep? ",
                        "Vervloet ",                          "Svendsdatter ",
                        "Vescovi ",                           "Taylor ",
                        "Vetorazzi ",                         "Tedesco ",
                        "Viale ",                             "Tedoldi ",
                        "Viana ",                             "Teganhe ",
                        "Vianna ",                            "Teixeira ",
                        "Vicente ",                           "Teles ",
                        "Vicini ",                            "Tereza ",
                        "Vida ",                              "Terossi ",
                        "Vidotti ",                           "Tessaro ",
                        "Viebrantz ",                         "Tessinari ",
                        "Vieira ",                            "Thiago ",
                        "Viens ",                             "Thirine ",
                        "Vilar ",                             "Thomaz ",
                        "Villa Nova ",                        "Tiborcio ",
                        "Villares da Costa ",                 "Toè ",
                        "Villares ",                          "Toledo ",
                        "Vinco ",                             "Tolfano ",
                        "Vitorazzi ",                         "Tom ",
                        "Vivacqua ",                          "Tomasi ",
                        "Vivaldi ",                           "Tomasine ",
                        "Volpato ",                           "Tomasini ",
                        "Volponi ",                           "Ton ",
                        "Voluzia ",                           "Tonet ",
                        "Vugarato ",                          "Toneto ",
                        "Werner ",                            "Tonin ",
                        "Woodward ",                          "Tonoli ",
                        "Xavier ",                            "Tonon ",
                        "Zampirolli ",                        "Torezani ",
                        "Zampirollo ",                        "Torres ",
                        "Zanardo ",                           "Toscano ",
                        "Zanata ",                            "Toste ",
                        "Zanatta ",                           "Tostes ",
                        "Zancanela ",                         "Tovar ",
                        "Zancanella ",                        "Toze ",
                        "Zanchetin ",                         "Tozi ",
                        "Zanchetta ",                         "Tozzi ",
                        "Zandonade ",                         "Trabach ",
                        "Zandonadi ",                         "Trancho ",
                        "Zanellato ",                         "Travaglia ",
                        "Zanette ",                           "Tres ",
                        "Zanetti ",                           "Trevisan ",
                        "Zanichelli ",                        "Trindade ",
                        "Zanivan ",                           "Tripeno ",
                        "Zanol ",                             "Tristão ",
                        "Zanon ",                             "Trombini ",
                        "Zanoni ",                            "Tronerin",
                        "Zanotti ",                           "Tsuchiya ",
                        "Zardo ",                             "Turbian ",
                        "Zavarise ",                          "Uliana ",
                        "Zavarize ",                          "Valiate ",
                        "Zerbone ",                           "Valiati ",
                        "Zicardi ",                           "Valiatti ",
                        "Ziviani ",                           "Valle ",
                        "Zocatelli ",                         "Valli ",
                        "Zoppi ",                             "Valoto ",
                        "Zorzal ",                            "Vanni ",
                        "Zorzanelli ",                        "Vantil ",
                        "Zuchi ",                             "Vanzan ",
                        "Zucoloto ",                          "Varandas ",
                        "Zulianni ",                          "Varella ",
                        "Zuqui ",                             "Vasconcelos ",
                        "Zuza "  ,                            "Vascotto ",
                        "Vasoler ",                           "Vaz "  };

            Random rnd = new Random();

            String LastName = null;

            switch (Total_LastName)
            {
                case 1:
                    LastName = lastname[rnd.Next(0, lastname.Length-1)].ToString();

                    break;
                case 2:

                    LastName = lastname[rnd.Next(0, lastname.Length - 1)].ToString();
                    LastName = LastName +" "+ lastname[rnd.Next(0, lastname.Length - 1)].ToString();

                    break;
                case 3:
                    LastName = lastname[rnd.Next(0, lastname.Length - 1)].ToString();
                    LastName = LastName + " " + lastname[rnd.Next(0, lastname.Length - 1)].ToString();
                    LastName = LastName + " " + lastname[rnd.Next(0, lastname.Length - 1)].ToString();

                    break;
                default:
                    LastName = lastname[rnd.Next(0, lastname.Length - 1)].ToString();
                    LastName = LastName + " " + lastname[rnd.Next(0, lastname.Length - 1)].ToString();
                    LastName = LastName + " " + lastname[rnd.Next(0, lastname.Length - 1)].ToString();
                    LastName = LastName + " " + lastname[rnd.Next(0, lastname.Length - 1)].ToString();

                    break;
            }



            return LastName; 

            // return "Nome";
        }


    }
}
